# Generated by Django 6.0 on 2025-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
