# Generated by Django 5.2.8 on 2025-12-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_workout_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
